"""
Find the number of distinct terms in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100
"""

if __name__ == "__main__":
    results = []

    for a in range(2, 101):
        for b in range(2,101):
            number = a ** b
            if number not in results:
                results.append(number)
    
    print(len(results))
